config/routes.rb
  Cook::Application.routes.draw do
  # Tags
  match 'tags/nameabc'      => 'tags#nameabc',      :via => 'get'
  match 'tags/popular'      => 'tags#popular',      :via => 'get'
  resources :tags
  
  #favorites
  match 'questions/:id/favorites' => 'favorites#create', :as => :favorites, :via => 'get'

  # post comment
  post 'comments/create'

  # Votes
  get "votes/vote_up"

  get "votes/vote_down"
  
  # Answers
  match 'questions/:id/latest'  => 'questions#answer_latest',  :via => 'get', :as => :answer_latest
  match 'questions/:id/vote'    => 'questions#answer_vote',    :via => 'get', :as => :answer_vote
  
  # Accepte answer
  match 'questions/:id/accept/:accept' => 'questions#accept', :as => :accept
  
  # Questions
  match 'questions/latest'  => 'questions#latest',  :via => 'get'
  match 'questions/active'  => 'questions#active',  :via => 'get'
  match 'questions/vote'    => 'questions#vote',    :via => 'get'
  match 'search' => 'questions#search', :via => 'get'
  
  # Unanswered
  match 'unanswered'        => 'unanswered#index',  :via => 'get'
  match 'unanswered/latest' => 'unanswered#latest', :via => 'get'
  match 'unanswered/active' => 'unanswered#active', :via => 'get'
  match 'unanswered/vote'   => 'unanswered#vote',   :via => 'get'
  
  # tagged
  match 'tagged/:tag'       => 'tagged#index',      :via => 'get',  :as => :tagged
  match 'tagged/:tag/latest'=> 'tagged#latest',     :via => 'get',  :as => :tagged_latest
  match 'tagged/:tag/active'=> 'tagged#active',     :via => 'get',  :as => :tagged_active 
  match 'tagged/:tag/vote'  => 'tagged#vote',       :via => 'get',  :as => :tagged_vote
  
  resources :questions do
    resources :answers do
      resources :comments
    end
    resources :comments
    get :autocomplete_tag_name, :on => :collection
  end
  
  # tagged
  match 'tagged/:tag'       => 'tagged#index',      :via => 'get',  :as => :tagged
  match 'tagged/:tag/latest'=> 'tagged#latest',     :via => 'get',  :as => :tagged_latest
  match 'tagged/:tag/active'=> 'tagged#active',     :via => 'get',  :as => :tagged_active 
  match 'tagged/:tag/vote'  => 'tagged#vote',       :via => 'get',  :as => :tagged_vote

  # Users
  match 'users/rp'          => 'users#rp',          :via => 'get'
  match 'users/oldest'      => 'users#oldest',      :via => 'get'

  # Devise
  devise_for :users
  
  resources :users

  root :to => "questions#index"

  end

app/models/question.rb
class Question < ActiveRecord::Base
  # NOTE: Questions belong to a user
  belongs_to :user
  
  # NOTE: one question has many answers
  has_many :answers,    :dependent => :destroy
  
  # validations
  validate :tags_count_must_within_one_to_five
  
  # Search Engine
  define_index do
    # fields
    indexes title, :sortable => true
    indexes body
    
    # attributes
    has created_at, updated_at
  end
  
  # tag plugin
  acts_as_taggable
  acts_as_taggable_on :tags
  
  # vote plugin
  acts_as_voteable
  
  # comment plugin
  acts_as_commentable
  
  # scope
  scope :latest, order("created_at DESC")
  scope :active, order("updated_at DESC")
  scope :vote, order("voted DESC")
  scope :unanswered, lambda { where(["accepted = 0"]) }
  
  # return tag list
  def tagged_list
    tagged.split(/,\s*/)
  end
  
  before_save :set_tagged_list

  private
    def set_tagged_list
      self.tagged = self.tag_list.to_s
    end
    
  protected
  
    def tags_count_must_within_one_to_five
      if self.tag_list.count > 5
        errors.add(:tag_list, "can not be more than 5 tags")
      elsif self.tag_list.count == 0
        errors.add(:tag_list, "must have 1 tag at least")
      end
    end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  
  before_filter :authenticate_user!, :only => [:new, :edit, :create, :update, :destroy]
  before_filter :find_question, :only => [:answer_latest, :answer_vote, :accept, :show, :edit, :update, :destroy]
  
  autocomplete :tag, :name, :full => true
  
  set_tab :questions
  set_tab :ask, :only => %w(new)
  set_tab :latest,  :navigation, :only => %w(index latest)
  set_tab :active,  :navigation, :only => %w(active)
  set_tab :vote,    :navigation, :only => %w(vote)
  
  set_tab :answer_latest, :navigation, :only => %w(answer_latest)
  set_tab :answer_oldest, :navigation, :only => %w(answer_oldest)
  set_tab :answer_vote,   :navigation, :only => %w(show answer_vote)

  def index
    @questions = pagination Question.latest
  end
  
  def search
    @questions = pagination Question.search params[:search]
    render :index
  end

  def latest
    @questions = pagination Question.latest
    render :index
  end
  
  def active
    @questions = pagination Question.active
    render :index
  end
  
  def vote
    @questions = pagination Question.vote
    render :index
  end
  
  def answer_latest
    @answers = pagination @question.answers.latest
    render :show
  end
  
  def answer_vote
    @answers = pagination @question.answers.vote
    render :show
  end
  
  def accept
    @question.update_attributes( :accepted => params[:accept] )
    
    # hack
    answer = Answer.find(params[:accept])
    answer.update_attributes( :voted => answer.voted + 27367, :created_at => -2010.years.ago(answer.created_at) )
    
    save_event(s=current_user,e='accept',t=answer)
    
    redirect_to @question
  end
  
  def show
    @answers = pagination @question.answers.vote
    # update viewed
    if session["viewed_#{@question.id}"] == nil
      session["viewed_#{@question.id}"] = 1
      @question.update_attributes(:viewed => @question.viewed+1)
    end
  end

  def new
    @question = current_user.questions.build
  end

  def edit
  end

  def create
    @question = current_user.questions.build(params[:question])
    @question.html_body = BlueCloth.new(coderay(@question.body)).to_html

    if @question.save
      redirect_to(@question, :notice => 'Question was successfully created.')
    else
      render :new
    end
  end

  def update
    @question.html_body = BlueCloth.new(coderay(params[:question][:body])).to_html
    @question.save

    if @question.update_attributes(params[:question])
      redirect_to(@question, :notice => 'Question was successfully updated.')
    else
      render :edit
    end
  end

  def destroy
    @question.destroy

    redirect_to(questions_url)
  end
  
  protected
    def find_question
      @question = Question.find(params[:id])
    end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.erb
<div id="editor">
	<%= form_for(@question) do |f| %>
	    <%= f.text_field :title,	:class => 'editor_element editor_title' %>
		<div id='wmd-button-bar'></div>
	    <%= f.text_area :body,		:class => 'editor_element editor_body editor_fontstyle resizable', :id => 'wmd-input' %>
		<div id='wmd-preview' class='editor_fontstyle'></div>
		<%= f.text_field :tag_list, :autocomplete => autocomplete_tag_name_questions_path, :class => 'editor_element editor_tags' %>
	    <%= f.submit '提交', :class => 'submit' %>
	<% end %>
</div>
<%= javascript_include_tag 'jquery.tar', 'wmd', 'showdown', 'autocomplete-rails' %>

app/views/questions/edit.html.erb
<div class="question-header">
	<h1>编辑问题</h1>
</div>
<%= render :partial => 'form', :locals => { :button_name => '确认编辑' } %>

app/views/questions/index.html.erb
<div id="list">
<div class="subheader">
	<h1>全部问题</h1>
	<%= tabs_tag(:namespace => :navigation, :builder => ApplicationHelper::MenuTabBuilder, :open_tabs => { :class => "tabs" }) do |tab| %>
		<%= tab.latest	'最新问题',	questions_latest_url %>
		<%= tab.active	'最近更新',	questions_active_url %>
		<%= tab.vote	'最多投票',	questions_vote_url %>
	<% end %>
</div>
	<%= render :partial => 'partials/question', :collection => @questions %>
</div>
<div id="sidebar">
	<%= render 'partials/intro' %>
	<%= render 'partials/recent_tag' %>
</div>
<%= will_paginate @questions %>

app/views/questions/new.html.erb
<%= render 'form' %>

app/views/questions/show.html.erb
<div class="question-header">
	<h1><%= link_to @question.title, @question %></h1>
</div>
<div class="content">
	<div class="post">
		<div class="left">
			<%= render :partial => 'partials/vote', :object => @question %>
		</div>
		<div class="right">
			<div class="post-text">
				<%= safe_html @question.html_body %>
			</div>
			<div class="permission">
				<%= link_to '编辑', [:edit,@question] if current_user and current_user.id == @question.user_id %>
			</div>
			<div class="user_stats">
				<div class="timestamp">
					ask <span style="font-weight:bold"><%= time_ago_in_words @question.created_at %></span> ago
				</div>
				<%= render :partial => 'partials/user', :object => @question.user %>
			</div>
			<%= render :partial => 'partials/comment', :object => @question, :as => :qora %>
		</div>
	</div>
	<div id="answers">
		<div id="answers-header">
			<div class="subheader">
				<h2><%= "#{@question.answers.size} 个答案" if @question.answers.present? %></h2>
				<%= tabs_tag(:namespace => :navigation, :builder => ApplicationHelper::MenuTabBuilder, :open_tabs => { :class => "tabs" }) do |tab| %>
					<%= tab.answer_vote		'投票',		answer_vote_url %>
					<%= tab.answer_latest	'最新',	answer_latest_url %>
				<% end if @question.answers.present? %>
			</div>
		</div>
		<%= render :partial => 'partials/answer', :collection => @answers %>
		<%= render :partial => @answer = @question.answers.build %>
	</div>
</div>