config/routes.rb
  Cook::Application.routes.draw do
  # Tags
  match 'tags/nameabc'      => 'tags#nameabc',      :via => 'get'
  match 'tags/popular'      => 'tags#popular',      :via => 'get'
  resources :tags
  
  #favorites
  match 'questions/:id/favorites' => 'favorites#create', :as => :favorites, :via => 'get'

  # post comment
  post 'comments/create'

  # Votes
  get "votes/vote_up"

  get "votes/vote_down"
  
  # Answers
  match 'questions/:id/latest'  => 'questions#answer_latest',  :via => 'get', :as => :answer_latest
  match 'questions/:id/vote'    => 'questions#answer_vote',    :via => 'get', :as => :answer_vote
  
  # Accepte answer
  match 'questions/:id/accept/:accept' => 'questions#accept', :as => :accept
  
  # Questions
  match 'questions/latest'  => 'questions#latest',  :via => 'get'
  match 'questions/active'  => 'questions#active',  :via => 'get'
  match 'questions/vote'    => 'questions#vote',    :via => 'get'
  match 'search' => 'questions#search', :via => 'get'
  
  # Unanswered
  match 'unanswered'        => 'unanswered#index',  :via => 'get'
  match 'unanswered/latest' => 'unanswered#latest', :via => 'get'
  match 'unanswered/active' => 'unanswered#active', :via => 'get'
  match 'unanswered/vote'   => 'unanswered#vote',   :via => 'get'
  
  # tagged
  match 'tagged/:tag'       => 'tagged#index',      :via => 'get',  :as => :tagged
  match 'tagged/:tag/latest'=> 'tagged#latest',     :via => 'get',  :as => :tagged_latest
  match 'tagged/:tag/active'=> 'tagged#active',     :via => 'get',  :as => :tagged_active 
  match 'tagged/:tag/vote'  => 'tagged#vote',       :via => 'get',  :as => :tagged_vote
  
  resources :questions do
    resources :answers do
      resources :comments
    end
    resources :comments
    get :autocomplete_tag_name, :on => :collection
  end
  
  # tagged
  match 'tagged/:tag'       => 'tagged#index',      :via => 'get',  :as => :tagged
  match 'tagged/:tag/latest'=> 'tagged#latest',     :via => 'get',  :as => :tagged_latest
  match 'tagged/:tag/active'=> 'tagged#active',     :via => 'get',  :as => :tagged_active 
  match 'tagged/:tag/vote'  => 'tagged#vote',       :via => 'get',  :as => :tagged_vote

  # Users
  match 'users/rp'          => 'users#rp',          :via => 'get'
  match 'users/oldest'      => 'users#oldest',      :via => 'get'

  # Devise
  devise_for :users
  
  resources :users

  root :to => "questions#index"

  end

app/views/partials/_accept.html.erb
<% if answer.question.accepted ==0 %>
	<% if current_user and answer.user_id == current_user.id %>
		<div class="accept" id="accept_<%= answer.id %>">
			<%= link_to '', accept_url(:id => answer.question.id, :accept => answer.id), :class => "accept" %>
		</div>
	<% end %>
<% elsif answer.question.accepted == answer.id %>
	<div class="accepted"></div>
<% end -%>

app/views/partials/_answer.html.erb
<%= div_for answer do %>
<div class="post-content">
	<div class="left">
		<% answer.voted -= 27367 if answer.voted >= 10000
		   answer.created_at =  2010.years.ago(answer.created_at) if answer.created_at.year > 3000 %>
		<%= render :partial => 'partials/vote', :object => answer %>
		<%= render :partial => 'partials/accept', :object => answer, :as => :answer %>
	</div>
	<div class="right">
		<div class="post-text">
			<%= safe_html answer.html_body%>
		</div>
		<div class="operation">
			<%= link_to '编辑', [:edit,answer.question,answer] if current_user and current_user.id == answer.user_id %>
		</div>
		<div class="user_stats">
			<div class="timestamp">
				ask <span style="font-weight:bold"><%= time_ago_in_words @question.created_at %></span> ago
			</div>
			<%= render :partial => 'partials/user', :object => @question.user %>
		</div>
		<%= render :partial => 'partials/comment', :object => answer, :as => :qora %>
	</div>
</div>
<% end %>

app/views/partials/_comment.html.erb
<div id="comments_<%= qora.class %>_<%= qora.id %>" class="comments">
	<%= render :partial => "comments/show_comment", :collection => qora.comments %>
</div>
<div id="create_comment_<%= qora.class %>_<%= qora.id %>" class="create_comment" style="display:none">
	<%= render :partial => "comments/comment", :locals => {:commentable => qora.class.name, :id => qora.id} %>
</div>
<div id="add_comment_<%= qora.class %>_<%= qora.id %>" class="add_comment">
	<% if qora.class.name == "Question" %>
		<%= link_to '添加回复', new_question_comment_path(qora), :remote => true %>
	<% else %>
		<%= link_to '添加回复', new_question_answer_comment_path(qora.question,qora), :remote => true %>
	<% end %>
</div>

app/views/partials/_intro.html.erb
<div id="intro">
	Return 0 是一个免费，快速，简单，社区驱动的专业苹果软硬件问答网站。<br/>
	Only Apple.
</div>

app/views/partials/_personal_answer.html.erb
<div class="answer_summary">
	<%= link_to answer.question.title, answer.question %>
</div>

app/views/partials/_personal_question.html.erb
<%= div_for question do %>
<div class="stats">
	<%= vote_stats(question.voted) %>
	<%= view_stats(question.viewed) %>
</div>
<div class="summary">
	<h3><%= link_to question.title, question %></h3>
	<div class="excerpt">
		<%= safe_html truncate(question.body, :length => 60) %>
	</div>
	<div class="tags">
		<% question.tagged_list.each do |tag| %>
			<%= link_to tag, tagged_url(:tag => tag), :class => 'tag' %>
		<% end -%>
	</div>
	<div class="object_info">
		<div class="action-time">
			ask <span style="font-weight:bold"><%= time_ago_in_words question.created_at %></span> ago
		</div>
	</div>
</div>
<% end %>

app/views/partials/_question.html.erb
<%= div_for question do %>
<div class="stats">
	<div class="voted">
		<%= to_k question.voted %> 投票
	</div>
	<% if question.accepted != 0
      answer_status = "acp"
    elsif question.answers.count > 0
      answer_status = "ans"
    else
      answer_status = "una"
    end %>
	<div class="answered <%= answer_status %>">
		<%= to_k question.answered %> 答案
	</div>
	<div class="viewed">
		<%= to_k question.viewed %> 浏览
	</div>
</div>
<div class="summary">
	<h3><%= link_to question.title, question %></h3>
	<div class="excerpt">
		<%= question.html_body.gsub(/<\/?[^>]*>/,  "") %>
	</div>
	<div class="msg">
		ask <span style="font-weight:bold"><%= time_ago_in_words question.created_at %></span> ago
	</div>
	<div class="tags">
		<% question.tagged_list.each do |tag| %>
			<%= link_to tag, tagged_url(:tag => tag), :class => 'tag' %>
		<% end -%>
	</div>
</div>
<% end -%>

app/views/partials/_recent_tag.html.erb
<div id="recent_tag">
	<h2>最新标签</h2>
</div>

app/views/partials/_site_stats.html.erb
<table class="stats_table">
	<tr>
		<th><%= Question.all.count %></th>
		<th>问题</th>
	</tr>
	<tr>
		<th><%= Answer.all.count %></th>
		<th>答案</th>
	</tr>
	<tr>
		<th><%= number_to_percentage( 1 - Question.unanswered.count / Question.all.count, :precision => 1 ) %></th>
		<th>解决</th>
	</tr>
	<tr>
		<th><%= User.all.count %></th>
		<th>用户</th>
	</tr>
</table>

app/views/partials/_tag.html.erb
<div class="tag_package">
	<%= link_to tag, tagged_url(:tag => tag.name), :class => 'package_tag' %> <%= tag.count %>
</div>

app/views/partials/_user.html.erb
<div class="user_card" style="margin-bottom:10px">
	<div class="avatar">
		<%= image_tag user.gravatar_url(:size => 32)%>
	</div>
	<div class="user_name">
		<%= link_to user.profile.full_name, user %>
	</div>
	<div class="user_rp">
		<%= to_k user.reputation %>
	</div>
</div>

app/views/partials/_user_package.html.erb
<div class="user_card package">
	<div class="small_gravatar">
		<%= image_tag user.gravatar_url(:size => 32) %>
	</div>
	<div class="user_text">
		<div class="user_name">
			<%= link_to user.profile.full_name, user %>
		</div>
		<div class="user_reputation">
			<%= to_k user.reputation %>
		</div>
	</div>
</div>

app/views/partials/_vote.html.erb
<%= link_to '', {:controller => :votes, :action => :vote_up, :voteable => vote.class.name, :id => vote.id}, :remote => true, :class => "vote-up" %>
<div class="voted_number" id="vote_<%= vote.class %>_<%= vote.id %>"><%= to_k vote.voted %></div>
<%= link_to '', {:controller => :votes, :action => :vote_down, :voteable => vote.class.name, :id => vote.id}, :remote => true, :class => "vote-down" %>