config/routes.rb
  Cook::Application.routes.draw do
  # Tags
  match 'tags/nameabc'      => 'tags#nameabc',      :via => 'get'
  match 'tags/popular'      => 'tags#popular',      :via => 'get'
  resources :tags
  
  #favorites
  match 'questions/:id/favorites' => 'favorites#create', :as => :favorites, :via => 'get'

  # post comment
  post 'comments/create'

  # Votes
  get "votes/vote_up"

  get "votes/vote_down"
  
  # Answers
  match 'questions/:id/latest'  => 'questions#answer_latest',  :via => 'get', :as => :answer_latest
  match 'questions/:id/vote'    => 'questions#answer_vote',    :via => 'get', :as => :answer_vote
  
  # Accepte answer
  match 'questions/:id/accept/:accept' => 'questions#accept', :as => :accept
  
  # Questions
  match 'questions/latest'  => 'questions#latest',  :via => 'get'
  match 'questions/active'  => 'questions#active',  :via => 'get'
  match 'questions/vote'    => 'questions#vote',    :via => 'get'
  match 'search' => 'questions#search', :via => 'get'
  
  # Unanswered
  match 'unanswered'        => 'unanswered#index',  :via => 'get'
  match 'unanswered/latest' => 'unanswered#latest', :via => 'get'
  match 'unanswered/active' => 'unanswered#active', :via => 'get'
  match 'unanswered/vote'   => 'unanswered#vote',   :via => 'get'
  
  # tagged
  match 'tagged/:tag'       => 'tagged#index',      :via => 'get',  :as => :tagged
  match 'tagged/:tag/latest'=> 'tagged#latest',     :via => 'get',  :as => :tagged_latest
  match 'tagged/:tag/active'=> 'tagged#active',     :via => 'get',  :as => :tagged_active 
  match 'tagged/:tag/vote'  => 'tagged#vote',       :via => 'get',  :as => :tagged_vote
  
  resources :questions do
    resources :answers do
      resources :comments
    end
    resources :comments
    get :autocomplete_tag_name, :on => :collection
  end
  
  # tagged
  match 'tagged/:tag'       => 'tagged#index',      :via => 'get',  :as => :tagged
  match 'tagged/:tag/latest'=> 'tagged#latest',     :via => 'get',  :as => :tagged_latest
  match 'tagged/:tag/active'=> 'tagged#active',     :via => 'get',  :as => :tagged_active 
  match 'tagged/:tag/vote'  => 'tagged#vote',       :via => 'get',  :as => :tagged_vote

  # Users
  match 'users/rp'          => 'users#rp',          :via => 'get'
  match 'users/oldest'      => 'users#oldest',      :via => 'get'

  # Devise
  devise_for :users
  
  resources :users

  root :to => "questions#index"

  end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  # :database_authenticatable, :registerable, :recoverable
  devise :openid_authenticatable, :rememberable, :trackable

  # Setup accessible (or protected) attributes for your model
  # :password, :password_confirmation,
  attr_accessible :email, :remember_me, :identity_url
  
  def self.create_from_identity_url(identity_url)
    self.create(:identity_url => identity_url)
  end
  
  def self.openid_required_fields
    ["email", "http://axschema.org/contact/email"]
  end
  
  def openid_fields=(fields)
    fields.each do |key, value|
      # Some AX providers can return multiple values per key
      if value.is_a? Array
        value = value.first
      end

      case key.to_s
        when "email", "http://axschema.org/contact/email"
          self.email = value
        else
          logger.error "Unknown OpenID field: #{key}"
      end
    end
  end
  
  has_many :questions,  :dependent => :destroy
  has_many :answers,    :dependent => :destroy
  has_one :profile,     :dependent => :destroy
  
  # some scopes
  scope :rp,      order("reputation DESC")
  scope :oldest,  order("created_at ASC")
  
  # vote plugin
  acts_as_voter
  has_karma(:questions, :as => :user)
  
  # gravatar plugin
  is_gravtastic!
  
  # create a profile after user sign up
  after_create :create_profile
  
  private
    def create_profile
      self.profile ||= Profile.new(:first_name => "无名", :last_name => "氏")
      self.save
    end
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_filter :find_user, :only => [:show, :edit, :update]
  
  set_tab :users
  
  set_tab :rp,      :navigation, :only => %w(index rp)
  set_tab :oldest,  :navigation, :only => %w(oldest)  
  

  def index
    @users = pagination User.rp
  end
  
  def oldest
    @users = pagination User.oldest
    render :index
  end
  
  def rp
    @users = pagination User.rp
    render :index
  end
  
  def show
    @questions = pagination(@user.questions,5)
  end
  
  def edit
    @profile = @user.profile
  end
  
  def update
    @profile = @user.profile
    if @profile.update_attributes(params[:profile])
      redirect_to @user
    else
      render :edit
    end
  end
  
  protected
    def find_user
      @user = User.find(params[:id])
    end
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="parentheader">
	<h1><%= @profile.full_name %> - 编辑</h1>
</div>
<div id="left_panel">
	<div class="big_gravatar">
		<%= image_tag @user.gravatar_url(:size => 128) %>
	</div>
	<div class="grid">
		<div class="change_avatar">
			<%= link_to '更换头像', 'http://www.gravatar.com/' %>
		</div>
	</div>
</div>
<%= form_for(@profile,:url => { :action => 'update' }) do |f| %>
<div id="center_panel">
	<table>
		<tbody>
			<tr>
				<td class = "label">姓</td>
				<td><%= f.text_field :last_name, :class => 'profile_field' %></td>
			</tr>
			<tr>
				<td class  = "label">名</td>
				<td><%= f.text_field :first_name, :class => 'profile_field' %></td>
			</tr>
			<tr>
				<td class  = "label">生日</td>
				<td><%= f.text_field :birth, :class => 'profile_field' %></td>
			</tr>
			<tr>
				<td class  = "label">性别</td>
				<td><%= f.text_field :gender, :class => 'profile_field' %></td>
			</tr>
			<tr>
				<td class  = "label">网站</td>
				<td><%= f.text_field :website, :class => 'profile_field' %></td>
			</tr>
			<tr>
				<td class  = "label">所在地</td>
				<td><%= f.text_field :location, :class => 'profile_field' %></td>
			</tr>
		</tbody>
	</table>
</div>
<div id="edit_me">
	<div id='wmd-button-bar'></div>
    <%= f.text_area :me, :class => 'editor_element editor_body editor_fontstyle resizable', :id => 'wmd-input' %>
	<div id='wmd-preview' class='editor_fontstyle'></div>
</div>
<%= f.submit '提交', :class => 'submit' %>
<% end %>
<%= javascript_include_tag 'jquery.tar', 'wmd', 'showdown', 'autocomplete-rails' %>

app/views/users/index.html.erb
<div class="parentheader">
	<h1>全部用户</h1>
	<%= tabs_tag(:namespace => :navigation, :builder => ApplicationHelper::MenuTabBuilder, :open_tabs => { :class => "tabs" }) do |tab| %>
		<%= tab.rp 		'RP',		users_rp_url %>
		<%= tab.oldest 	'时间',	users_oldest_url%>
	<% end %>
</div>
<%= render :partial => 'partials/user_package', :collection => @users, :as => :user %>
<%= will_paginate @users %>

app/views/users/show.html.erb
<div class="parentheader">
	<h1><%= @user.profile.full_name %></h1>
</div>
<div id="left_panel">
	<div class="big_gravatar">
		<%= image_tag @user.gravatar_url(:size => 128) %>
	</div>
	<div class="grid">
		<div class="reputation">
			<%= @user.reputation %><span class="rp_label"> rp</span>
		</div>
	</div>
</div>
<div id="center_panel">
	<div id="profile_sum">
		<div id="profile_opt">
			<%= link_to '编辑', [:edit, @user] %>
		</div>
	</div>
	<table>
		<tbody>
		<tr>
			<td class="label">E-Mail</td>
			<td><%= @user.email %></td>
		</tr>
		<tr>
			<td class="label">英名</td>
			<td><%= @user.profile.full_name %></td>
		</tr>
		<tr>
			<td class="label">年龄</td>
			<td><%= Time.now.year - @user.profile.birth.year if @user.profile.birth%></td>
		</tr>
		<tr>
			<td class="label">性别</td>
			<td><%= @user.profile.gender %></td>
		</tr>
		<tr>
			<td class="label">加入时间</td>
			<td><%= time_ago_in_words @user.created_at %></td>
		</tr>
		<tr>
			<td class="label">登录时间</td>
			<td><%= time_ago_in_words @user.current_sign_in_at %></td>
		</tr>
		<tr>
			<td class="label">网站</td>
			<td><%= link_to @user.profile.website, @user.profile.website %></td>
		</tr>
		<tr>
			<td class="label">所在地</td>
			<td><%= @user.profile.location %></td>
		</tr>
		</tbody>
	</table>
</div>
<div id="right_panel">
	<%= @user.profile.me %>
</div>
<div class="area_header">
	<span class="summarycount"><%= @user.questions.count %></span>
	<span class="summaryheader">问题</span>
</div>
<div class="list">
	<%= render :partial => 'partials/question', :collection => @questions %>
	<%= will_paginate @questions %>
</div>