config/routes.rb
  Cook::Application.routes.draw do
  # Tags
  match 'tags/nameabc'      => 'tags#nameabc',      :via => 'get'
  match 'tags/popular'      => 'tags#popular',      :via => 'get'
  resources :tags
  
  #favorites
  match 'questions/:id/favorites' => 'favorites#create', :as => :favorites, :via => 'get'

  # post comment
  post 'comments/create'

  # Votes
  get "votes/vote_up"

  get "votes/vote_down"
  
  # Answers
  match 'questions/:id/latest'  => 'questions#answer_latest',  :via => 'get', :as => :answer_latest
  match 'questions/:id/vote'    => 'questions#answer_vote',    :via => 'get', :as => :answer_vote
  
  # Accepte answer
  match 'questions/:id/accept/:accept' => 'questions#accept', :as => :accept
  
  # Questions
  match 'questions/latest'  => 'questions#latest',  :via => 'get'
  match 'questions/active'  => 'questions#active',  :via => 'get'
  match 'questions/vote'    => 'questions#vote',    :via => 'get'
  match 'search' => 'questions#search', :via => 'get'
  
  # Unanswered
  match 'unanswered'        => 'unanswered#index',  :via => 'get'
  match 'unanswered/latest' => 'unanswered#latest', :via => 'get'
  match 'unanswered/active' => 'unanswered#active', :via => 'get'
  match 'unanswered/vote'   => 'unanswered#vote',   :via => 'get'
  
  # tagged
  match 'tagged/:tag'       => 'tagged#index',      :via => 'get',  :as => :tagged
  match 'tagged/:tag/latest'=> 'tagged#latest',     :via => 'get',  :as => :tagged_latest
  match 'tagged/:tag/active'=> 'tagged#active',     :via => 'get',  :as => :tagged_active 
  match 'tagged/:tag/vote'  => 'tagged#vote',       :via => 'get',  :as => :tagged_vote
  
  resources :questions do
    resources :answers do
      resources :comments
    end
    resources :comments
    get :autocomplete_tag_name, :on => :collection
  end
  
  # tagged
  match 'tagged/:tag'       => 'tagged#index',      :via => 'get',  :as => :tagged
  match 'tagged/:tag/latest'=> 'tagged#latest',     :via => 'get',  :as => :tagged_latest
  match 'tagged/:tag/active'=> 'tagged#active',     :via => 'get',  :as => :tagged_active 
  match 'tagged/:tag/vote'  => 'tagged#vote',       :via => 'get',  :as => :tagged_vote

  # Users
  match 'users/rp'          => 'users#rp',          :via => 'get'
  match 'users/oldest'      => 'users#oldest',      :via => 'get'

  # Devise
  devise_for :users
  
  resources :users

  root :to => "questions#index"

  end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cook</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag 'jquery', 'jui', 'rails', 'application' %>
  <%= csrf_meta_tag %>
</head>
<body>
	<div id="container">
		<div id="menu">
			<% if user_signed_in? %>
				<div class="micro_gravatar">
					<%= image_tag current_user.gravatar_url(:size => 20) %>
				</div>
				<%= link_to current_user.profile.full_name, current_user %> 
				<%= link_to current_user.reputation %> | 
				<%= link_to "注销", destroy_user_session_path %>
			<% else %>
				<%= link_to "使用OpenID登录", new_user_session_path %>
			<% end %>
		</div>
		<div id="return0">
			<%= link_to image_tag("return0.png"), root_url %>
		</div>
		<%= tabs_tag(:builder => ApplicationHelper::NavTabBuilder, :open_tabs => { :class => "navigation" }) do |tab| %>
			<%= tab.questions	'问题',	questions_path %>
			<%= tab.tags		'标签',	tags_path %>
			<%= tab.users		'用户',	users_path %>
			<%= tab.unanswered	'待解决',	unanswered_path %>
			<%= tab.ask			'提问',	new_question_path %>
		<% end %>
		<% form_tag search_path, :method => :get do %>
		<%= text_field_tag :search, params[:search] %>
		<% end %>
		<div id="wrapper">
			<%= yield %>
		</div>
	</div>
	<div id="footer">
		<div id="cpright">
			Copyright © 2010 Return 0 Team. 保留所有权利。 | revision: 2010.9.29 | 
			用户贡献的内容采用<a rel="license" href="http://creativecommons.org/licenses/by-sa/2.5/">知识共享署名-相同方式共享 2.5 未本地化版本许可协议</a>进行许可。
		</div>
	</div>
</body>
</html>